// Template: Models (ApiModel.t4) version 4.0

// This code was generated by AMF Server Scaffolder

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace practica2_mtis.Empleado.Models
{
    public partial class Empleado
    {
        

        [Required]
        [MaxLength(10)]
        [MinLength(0)]
        public string DNI { get; set; }

        [MaxLength(50)]
        [MinLength(0)]
        public string Nombre { get; set; }

        [MaxLength(50)]
        [MinLength(0)]
        public string Apellidos { get; set; }

        [MaxLength(200)]
        [MinLength(0)]
        public string Direccion { get; set; }

        [MaxLength(20)]
        [MinLength(0)]
        public string Poblacion { get; set; }

        [MaxLength(10)]
        [MinLength(0)]
        public string Telefono { get; set; }

        [MaxLength(50)]
        [MinLength(0)]
        public string Email { get; set; }

        [MinLength(0)]
        public string Fecha_nacimiento { get; set; }

        [MaxLength(50)]
        [MinLength(0)]
        public string NSS { get; set; }

        [MaxLength(50)]
        [MinLength(0)]
        public string IBAN { get; set; }
    } // end class

} // end Models namespace

