// Template: Base Controller (ApiControllerBase.t4) version 4.0

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Http;
using System.Web.Http.Description;
using practica2_mtis.Empleado.Models;

// Do not modify this file. This code was generated by AMF Server Scaffolder

namespace practica2_mtis.Empleado
{
    [RoutePrefix("Empleado")]
    public partial class EmpleadoController : ApiController
    {


/// <summary>
		/// Crea nuevo empleado - /Empleado/nuevo
		/// </summary>
		/// <param name="empleado"></param>
		/// <param name="restkey"></param>
		/// <returns>MultipleEmpleadoNuevoPost</returns>
        [ResponseType(typeof(MultipleEmpleadoNuevoPost))]
        [HttpPost]
        [Route("nuevo")]
        public virtual IHttpActionResult PostBase([FromBody] practica2_mtis.Empleado.Models.Empleado empleado,[FromUri] string restkey)
        {
            // Do not modify this code
                        return  ((IEmpleadoController)this).Post(empleado,restkey);
                    }

/// <summary>
		/// Borrar empleado - /Empleado/borrar
		/// </summary>
		/// <param name="content"></param>
		/// <param name="restkey"></param>
		/// <param name="dni"></param>
		/// <returns>MultipleEmpleadoBorrarPost</returns>
        [ResponseType(typeof(MultipleEmpleadoBorrarPost))]
        [HttpPost]
        [Route("borrar")]
        public virtual IHttpActionResult PostBorrarBase([FromBody] string content,[FromUri] string restkey,[FromUri] string dni)
        {
            // Do not modify this code
                        return  ((IEmpleadoController)this).PostBorrar(content,restkey,dni);
                    }

/// <summary>
		/// Modificar empleado - /Empleado/modificar
		/// </summary>
		/// <param name="empleado"></param>
		/// <param name="restkey"></param>
		/// <returns>MultipleEmpleadoModificarPut</returns>
        [ResponseType(typeof(MultipleEmpleadoModificarPut))]
        [HttpPut]
        [Route("modificar")]
        public virtual IHttpActionResult PutBase([FromBody] practica2_mtis.Empleado.Models.Empleado empleado,[FromUri] string restkey)
        {
            // Do not modify this code
                        return  ((IEmpleadoController)this).Put(empleado,restkey);
                    }

/// <summary>
		/// Consultar empleado - /Empleado/consultar
		/// </summary>
		/// <param name="restkey"></param>
		/// <param name="dni"></param>
		/// <returns>MultipleEmpleadoConsultarGet</returns>
        [ResponseType(typeof(MultipleEmpleadoConsultarGet))]
        [HttpGet]
        [Route("consultar")]
        public virtual IHttpActionResult GetBase([FromUri] string restkey,[FromUri] string dni)
        {
            // Do not modify this code
                        return  ((IEmpleadoController)this).Get(restkey,dni);
                    }
    }
}
