// Template: Models (ApiModel.t4) version 4.0

// This code was generated by AMF Server Scaffolder

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using practica2_mtis.Empleado.Models;
using practica2_mtis.Seguridad.Models;

namespace practica2_mtis.Utilidades.Models
{
    /// <summary>
    /// Multiple Response Types Ipbool, Error
    /// </summary>
    public partial class MultipleUtilidadesValidarNIFGet
    {
        

        /// <summary>
        /// Validacion correcta 
        /// </summary>

        public bool? Ipbool { get; set; }

        /// <summary>
        /// NIF invalido 
        /// </summary>

        public Error Error { get; set; }
    } // end class

} // end Models namespace

