// Template: Models (ApiModel.t4) version 4.0

// This code was generated by AMF Server Scaffolder

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace practica2_mtis.Seguridad.Models
{
    /// <summary>
    /// Multiple Response Types Ipbool, Error
    /// </summary>
    public partial class MultipleSeguridadEliminarPermisosPost
    {
        

        /// <summary>
        /// Peticion correcta 
        /// </summary>

        public bool? Ipbool { get; set; }

        /// <summary>
        /// Ha habido un error en la peticion 
        /// </summary>

        public Error Error { get; set; }
    } // end class

} // end Models namespace

