// Template: Models (ApiModel.t4) version 4.0

// This code was generated by AMF Server Scaffolder

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using practica2_mtis.Seguridad.Models;

namespace practica2_mtis.Empleado.Models
{
    /// <summary>
    /// Multiple Response Types Empleado, Error
    /// </summary>
    public partial class MultipleEmpleadoConsultarGet
    {
        

        /// <summary>
        /// Empleado consultado correctamente 
        /// </summary>

        public Empleado Empleado { get; set; }

        /// <summary>
        /// Error 
        /// </summary>

        public Error Error { get; set; }
    } // end class

} // end Models namespace

