// Template: Base Controller (ApiControllerBase.t4) version 4.0

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Http;
using System.Web.Http.Description;
using practica2_mtis.Utilidades.Models;

// Do not modify this file. This code was generated by AMF Server Scaffolder

namespace practica2_mtis.Utilidades
{
    [RoutePrefix("Utilidades")]
    public partial class UtilidadesController : ApiController
    {


/// <summary>
		/// Valida el NIF de un usuario y devuelve cierto si es correcto o falso si no lo es - /Utilidades/validarNIF
		/// </summary>
		/// <param name="dni"></param>
		/// <param name="restkey"></param>
		/// <returns>MultipleUtilidadesValidarNIFGet</returns>
        [ResponseType(typeof(MultipleUtilidadesValidarNIFGet))]
        [HttpGet]
        [Route("validarNIF")]
        public virtual IHttpActionResult GetBase([FromUri] string dni,[FromUri] string restkey)
        {
            // Do not modify this code
                        return  ((IUtilidadesController)this).Get(dni,restkey);
                    }

/// <summary>
		/// valida el NAFSS de un usuario - /Utilidades/validarNAFSS
		/// </summary>
		/// <param name="dni"></param>
		/// <param name="restkey"></param>
		/// <returns>MultipleUtilidadesValidarNAFSSGet</returns>
        [ResponseType(typeof(MultipleUtilidadesValidarNAFSSGet))]
        [HttpGet]
        [Route("validarNAFSS")]
        public virtual IHttpActionResult GetValidarNAFSSBase([FromUri] string dni,[FromUri] string restkey)
        {
            // Do not modify this code
                        return  ((IUtilidadesController)this).GetValidarNAFSS(dni,restkey);
                    }

/// <summary>
		/// Valida el IBAN de un usuario - /Utilidades/validarIBAN
		/// </summary>
		/// <param name="dni"></param>
		/// <param name="restkey"></param>
		/// <returns>MultipleUtilidadesValidarIBANGet</returns>
        [ResponseType(typeof(MultipleUtilidadesValidarIBANGet))]
        [HttpGet]
        [Route("validarIBAN")]
        public virtual IHttpActionResult GetValidarIBANBase([FromUri] string dni,[FromUri] string restkey)
        {
            // Do not modify this code
                        return  ((IUtilidadesController)this).GetValidarIBAN(dni,restkey);
                    }
    }
}
